apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
subjects:
- kind: User
  name: "eks-user"  # Replace with the actual username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-user-pods  # Replace with the actual ClusterRole name
  apiGroup: rbac.authorization.k8s.io

